# Generated by Django 3.2.4 on 2021-11-23 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('p_apellido', models.CharField(max_length=20)),
                ('m_apellido', models.CharField(max_length=20)),
                ('rut', models.IntegerField(max_length=10)),
                ('correo', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.persona')),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.BooleanField()),
            ],
            bases=('core.persona',),
        ),
    ]
