# Generated by Django 3.2.4 on 2021-11-23 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.persona')),
                ('especialidad', models.CharField(choices=[('FM', 'Familiar'), ('PD', 'Pediatría'), ('IN', 'Interna'), ('SQ', 'Psiquiatría'), ('OP', 'Ortopedia'), ('OF', 'Oftalmología'), ('GN', 'General'), ('DT', 'Dermatología'), ('CD', 'Cardiología')], max_length=2)),
            ],
            bases=('core.persona',),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='sexo',
            field=models.CharField(choices=[('MJ', 'Mujer'), ('HM', 'Hombre')], max_length=2),
        ),
    ]
