# Generated by Django 3.2.4 on 2021-11-23 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20211123_1633'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disponibilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('colaccion_inicio', models.TimeField()),
                ('colaccion_fin', models.TimeField()),
                ('medico', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.medico')),
            ],
        ),
    ]
