# Generated by Django 3.2.4 on 2021-11-23 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20211123_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disponibilidad',
            name='creacion',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='hora',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
