# Generated by Django 3.2.4 on 2021-11-24 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_disponibilidad_creacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hora',
            name='hora_fin',
        ),
        migrations.RemoveField(
            model_name='hora',
            name='paciente',
        ),
        migrations.AlterField(
            model_name='hora',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
    ]
