# Generated by Django 3.2.4 on 2021-11-24 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20211124_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hora',
            name='fecha',
            field=models.DateField(),
        ),
    ]
