# Generated by Django 3.2.4 on 2021-11-25 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_cita'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='habilitada',
            field=models.BooleanField(default=True),
        ),
    ]
